diag.sh

diff --git a/.bin/shell-init/init-emacs b/.bin/shell-init/init-emacs
--- a/.bin/shell-init/init-emacs
+++ b/.bin/shell-init/init-emacs
@@ -2,9 +2,9 @@
 install_package emacs
 
 # install spacemacs
-if [ ! -d "~/.emacs.d" ]; then
-    mkdir ~/.emacs.d
-    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
+if [[ ! -d ~/.emacs.d ]]; then
+    mkdir -p ~/.emacs.d || { echo "Failed to create ~/.emacs.d"; exit 1; }
+    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d || { echo "Failed to clone Spacemacs"; rm -rf ~/.emacs.d; exit 1; }
 fi
 
 # Preferred editor for local and remote sessions
